services:
  api:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test.rule=Host(`test.dracon.uk`)"
      - "traefik.http.routers.test.entrypoints=websecure"
      - "traefik.http.routers.test.tls.certresolver=letsencrypt"
      - "traefik.http.services.test.loadbalancer.server.port=80"
    networks:
      - traefik-public
    restart: always
    depends_on:
      - redis
      - db

  redis:
    image: redis:7-alpine
    restart: always

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: citadel
      POSTGRES_USER: citadel
      POSTGRES_PASSWORD: citadel123
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  traefik-public:
    external: true

volumes:
  db_data:
